### ISSUE TITLE
Support for mounting datasets!

### ISSUE THREAD

**Issue by codeviking** [allenai/beaker-gantry#13]
It doesn't appear to be possible, but probably should be.

**Comment by codeviking** [comment]
Yup, and I think users would be allowed to provide multiple, right?

What if there was support for both mounting and creating a dataset from a directory of local files. I'm imaging I have a working directory like so:

```
data/
train.py
environment.yaml
```

Where `data/` is the training data I'm going to use, and ideally shouldn't be packaged with the code.

Maybe I could run this like so:

```
gantry run --dataset data/ ...
```

And we could handle `--dataset`s with only a path by:

1. First creating a dataset from the contents
2. Mounting the dataset at the same path in the workload

I think what you've proposed is the right first-step, but just thought I'd leave this idea there too! @mattf1n WDYT?

**Comment by epwalsh** [comment]
> Yup, and I think users would be allowed to provide multiple, right?

Yeup!

I like the idea of local datasets too.
