### ISSUE TITLE
Support for adding environment variables from both values and secrets

### ISSUE THREAD

**Issue by epwalsh** [allenai/beaker-gantry#21]
Might need two separate options, something like `--env 'NAME=VALUE'` and `--env-secret 'NAME=SECRET'`. Maybe we could also have a shortcut for the 2nd case: `--secret SECRET` which would be equivalent to `--env-secret SECRET=SECRET`.

**Comment by csarron** [comment]
Hi @epwalsh, is this feature implemented yet? I recently came across this issue when using Wandb, it requires setting the environment variable `WANDB_API_KEY` for authorization (https://docs.wandb.ai/guides/track/advanced/environment-variables#optional-environment-variables)
